# board: [ "nice_nano_v2" ]
# shield: [ "phil_left", "phil_right" ]
# - board: nice_nano
#   shield: phil_left
# - board: nice_nano
#   shield: phil_right

---
include:
  - board: nice_nano
    shield: philly
